package com.stjerncraft.controlpanel.api.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Put this on a class to generate a factory class with the name className + "Factory". This essentially decides where you place the factory class.
 * This factory class will contain a list of all DataObjects generated by the API, and the ability to create new instances of the generated class.
 * This will also allow for the Serialization and Deserialization of the given classes directly.
 * 
 * Note: Since multiple JARs might have used the API to generate DataObjects, we can't simply generate one global DataObjectFactory, as they would overwrite/conflict.
 * TODO: Add some kind of category? Allowing a Factory only to cover DataObjects with the same category/tag etc.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.CLASS)
public @interface DataObjectFactory {}
